//! Rendering a validated spec to each runtime's configuration file format.
//!
//! Both renderers are pure: they take a spec and return a string. Nothing here
//! reads the environment or the filesystem, so what a generated file can
//! contain is exactly what the caller validated.

use super::{AgentRuntimeConfigSpec, ConfigGenError, McpTransport};

/// The placeholder a forwarded environment variable is written as. The runtime
/// substitutes it from its own environment at spawn time; the value never
/// enters the file.
fn placeholder(name: &str) -> String {
    format!("${{{name}}}")
}

/// Renders the spec as a Claude project `.mcp.json` document.
///
/// The shape is the one `config_bridge::claude` reads back — a top-level
/// `mcpServers` object keyed by server name — with the stdio and `type: "http"`
/// entry shapes OpenSEO's published `plugins/openseo` manifests use.
///
/// Skills are not part of this file; they are placed on disk by
/// [`super::write_claude_project_config`].
///
/// # Errors
///
/// Returns [`ConfigGenError::Io`] if the document cannot be serialized, which
/// the validated spec makes unreachable but is surfaced rather than panicked on.
pub fn render_claude_mcp_json(spec: &AgentRuntimeConfigSpec) -> Result<String, ConfigGenError> {
    let mut servers = serde_json::Map::new();
    for (name, transport) in spec.servers_by_name() {
        let entry = match transport {
            McpTransport::Stdio {
                command,
                args,
                env_passthrough,
            } => {
                let mut env = serde_json::Map::new();
                for key in env_passthrough {
                    env.insert(key.clone(), serde_json::Value::String(placeholder(key)));
                }
                let mut obj = serde_json::Map::new();
                obj.insert("type".into(), serde_json::Value::String("stdio".into()));
                obj.insert("command".into(), serde_json::Value::String(command.clone()));
                obj.insert(
                    "args".into(),
                    serde_json::Value::Array(
                        args.iter()
                            .map(|a| serde_json::Value::String(a.clone()))
                            .collect(),
                    ),
                );
                obj.insert("env".into(), serde_json::Value::Object(env));
                serde_json::Value::Object(obj)
            }
            McpTransport::Http { url } => {
                let mut obj = serde_json::Map::new();
                obj.insert("type".into(), serde_json::Value::String("http".into()));
                obj.insert("url".into(), serde_json::Value::String(url.clone()));
                serde_json::Value::Object(obj)
            }
        };
        servers.insert(name.to_string(), entry);
    }

    let mut root = serde_json::Map::new();
    root.insert("mcpServers".into(), serde_json::Value::Object(servers));
    let mut rendered =
        serde_json::to_string_pretty(&serde_json::Value::Object(root)).map_err(|e| {
            ConfigGenError::Io {
                path: ".mcp.json".to_string(),
                source: e.to_string(),
            }
        })?;
    rendered.push('\n');
    Ok(rendered)
}

/// Renders the spec as a Codex `config.toml` document.
///
/// The shape is the one `config_bridge::codex::parse_mcp_servers` reads back —
/// one `[mcp_servers.<name>]` table per server.
///
/// The document is assembled rather than serialized through `toml::to_string`
/// so the emission order (scalars, then the nested `env` table) is fixed by this
/// code and cannot change with a map's iteration order. Every string goes
/// through `toml::Value`'s own escaping.
///
/// # Errors
///
/// Returns [`ConfigGenError`] never in practice; the signature matches
/// [`render_claude_mcp_json`] so callers handle both the same way.
pub fn render_codex_config_toml(spec: &AgentRuntimeConfigSpec) -> Result<String, ConfigGenError> {
    let mut out = String::new();
    out.push_str("# Generated by Buzz for a managed agent. Do not edit by hand.\n");
    out.push_str("# Values written as ${NAME} are placeholders the runtime expands\n");
    out.push_str("# from its own environment; no value is stored here.\n");
    for (name, transport) in spec.servers_by_name() {
        out.push_str(&format!("\n[mcp_servers.{name}]\n"));
        match transport {
            McpTransport::Stdio {
                command,
                args,
                env_passthrough,
            } => {
                out.push_str(&format!("command = {}\n", toml_string(command)));
                let rendered_args: Vec<String> = args.iter().map(|a| toml_string(a)).collect();
                out.push_str(&format!("args = [{}]\n", rendered_args.join(", ")));
                if !env_passthrough.is_empty() {
                    out.push_str(&format!("\n[mcp_servers.{name}.env]\n"));
                    for key in env_passthrough {
                        out.push_str(&format!("{key} = {}\n", toml_string(&placeholder(key))));
                    }
                }
            }
            McpTransport::Http { url } => {
                out.push_str(&format!("url = {}\n", toml_string(url)));
            }
        }
    }
    Ok(out)
}

/// A TOML-quoted, escaped string literal.
fn toml_string(value: &str) -> String {
    toml::Value::String(value.to_string()).to_string()
}
